### ISSUE TITLE
Personalizar enlaces de la cabecera

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/consul#4]
Ahora mismo los enlaces de la cabecera se renderizan en este partial: `app/views/shared/_top_links.html.erb`

![screen shot 2017-03-22 at 09 53 02](https://cloud.githubusercontent.com/assets/17616/24189457/5f9a7b3a-0ee5-11e7-97f8-146b92e60028.png)

Vamos a parametrizar esos enlaces:

1. extraer a settings las URLs de transparencia y open data, como está la de blog. Estudiar si vale la pena hacer que si el setting no está creado haga fallback a la configuración actual o no te muestre nada

2. Página de más información: integramos la comprobación con el nuevo MiniCMS o lo convertimos a setting?

3. Al final del listado de enlaces, incluir una llamada a un atributo de la configuración del site con un bloque de HTML (dependiente de la locale) para añadir enlaces nuevos.

**Comment by amaia** [comment]
En el punto 1 creo que es mejor hacer fallback al comportamiento actual, para no romper sitios que ya existan y actualicen el código. En el caso de que no queramos mostrar esas dos url podemos hacer una vista custom en instalaciones nuevas.

En el punto 2 lo que hay ahora (en el PR #8) es que si hay alguna página de CMS muestra sólo esas y si no hace fallback al comportamiento anterior, que es mostrar la vista existente en el código (custom o default), para no romper nada, yo creo que lo podemos dejar así, a no ser que veamos algún caso que no encaja.
