### ISSUE TITLE
Añadir Telegram como forma de contacto

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/consul#5]
Las redes sociales se integran de tres formas:

- como el enlace al _handle_ en el footer. Posiblemente haga falta una imagen en blanco sobre fondo negro (pedir a @martgnz)

- como el enlace a compartir en la lista de enlaces de compartir. Se hace con este formato de URL: `https://telegram.me/share/url?url=urlOfTheWebsite&text=TextToAccompany`. Va en el partial `/app/views/legislation/shared/_share_buttons.html.erb`

- en la gema [social-share-button](https://github.com/huacnlee/social-share-button) que ya soporta Telegram

**Comment by amaia** [comment]
#13 has been merged upstream
